apiVersion: v1
kind: Secret
metadata:
  name: crawler-executor-redis
  labels:
    app.kubernetes.io/name: crawler-executor
type: Opaque
stringData:
  fetch_queue_redis_url: CHANGE_ME_REDIS_URL
  redis_url: CHANGE_ME_REDIS_URL
---
apiVersion: v1
kind: Secret
metadata:
  name: crawler-executor-kafka
  labels:
    app.kubernetes.io/name: crawler-executor
type: Opaque
stringData:
  username: CHANGE_ME_KAFKA_USERNAME
  password: CHANGE_ME_KAFKA_PASSWORD
